/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public String goodbye(String name) {
        return "Good bye "+name;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
